FROM docker.io/rhel
RUN subscription-manager register --username SOME_NAME --password 'SOME_PASSWORD' --auto-attach
RUN yum install tar -y
RUN yum install libicu libuuid libcurl openssl libunwind -y
RUN yum install curl -y
RUN mkdir -p /Tools/DotNet
RUN cd /Tools/DotNet
RUN curl https://dotnetcli.blob.core.windows.net/dotnet/dev/Binaries/Latest/dotnet-centos-x64.latest.tar.gz > dotnet-centos-x64.latest.tar.gz
RUN echo 'Hey, Im a text file' | tee /Tools/DotNet/someFile.txt
RUN mkdir -p /Tools/DotNet/bin/dotnet
RUN gunzip dotnet-centos-x64.latest.tar.gz 
RUN tar -xf dotnet-centos-x64.latest.tar -C /Tools/DotNet/bin/dotnet
RUN rm /dotnet-centos-x64.latest.tar
RUN adduser rick
RUN echo a_password | passwd rick --stdin
RUN su - rick
RUN rm /home/rick/.bashrc
ADD altered_bashrc /home/rick/.bashrc
